# Generated by Django 3.0.7 on 2020-06-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("is_delicious", models.BooleanField(verbose_name="Вкусная")),
            ],
            options={"verbose_name": "пицца", "verbose_name_plural": "пицца",},
        ),
    ]
